### ISSUE TITLE
LibPcap not installed or jnetpcap.dll cannot be found

### ISSUE THREAD

**Issue by IbnRamli** [rtslab/EnergyBox#15]
Hi everyone,

I've ever installed EnergyBox before and didnt run well.
I've installed WinPcap, tried to put jnetpcap.dll in System and System32 folder, but still not work. There is Error said "LibPcap not installed or jnetpcap.dll cannot be found".
So I tried to back again to this site and there is so many commit and new informations in Readme.me.

Im still newby and really have no idea about how to run this app well. My Error still not resolved.
I believe there are something wrong about how I install it.
I really need some help here.
Hope You dont mind to show the step by step installing/run EnergyBox.

Thanks before.

note :
I used Windows 8 Pro and Netbeans 8.0.2

**Comment by jensgreen** [comment]
Should be solved by #16
